# _config.yml
title: Wiki
description: A man-handled wiki for the Islena-D&D campaign.
theme: minima

# Custom navigation links
header_pages:
  - index.md
  - Characterindex.md
  - Loot/Loot.md
  - Places/Places.md
  - Sessioni/Logsessions.md
  - about.md
